name: Packages Docs
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m pip install sphinx_rtd_theme
      - run: whereis sphinx-build
      - run: export PATH=/usr/local/bin/sphinx-build:$PATH
      - run: cd docs && make html
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build