name: Packages Docs
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: | 
          sudo apt-get install python3-sphinx
          python -m pip install --upgrade pip
          pip install sphinx_rtd_theme
      - run: cd docs && make html
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build